inherit_from: configs/Replica/replica_iLabel_plus.yaml
mapping:
  bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  marching_cubes_bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
data:
  input_folder: Datasets/Replica/room_0/Sequence_1
  output: output/Replica/room_0